/* Auto-generated by genmsg_cpp for file /home/rdro117/ros_workspace/beaconfinder/msg/Beacons.msg */
#ifndef BEACONFINDER_MESSAGE_BEACONS_H
#define BEACONFINDER_MESSAGE_BEACONS_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"
#include "beaconfinder/Beacon.h"

namespace beaconfinder
{
template <class ContainerAllocator>
struct Beacons_ : public ros::Message
{
  typedef Beacons_<ContainerAllocator> Type;

  Beacons_()
  : header()
  , numBeacons(0)
  , beacon()
  {
  }

  Beacons_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , numBeacons(0)
  , beacon(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _numBeacons_type;
  uint8_t numBeacons;

  typedef std::vector< ::beaconfinder::Beacon_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::beaconfinder::Beacon_<ContainerAllocator> >::other >  _beacon_type;
  std::vector< ::beaconfinder::Beacon_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::beaconfinder::Beacon_<ContainerAllocator> >::other >  beacon;


  ROS_DEPRECATED uint32_t get_beacon_size() const { return (uint32_t)beacon.size(); }
  ROS_DEPRECATED void set_beacon_size(uint32_t size) { beacon.resize((size_t)size); }
  ROS_DEPRECATED void get_beacon_vec(std::vector< ::beaconfinder::Beacon_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::beaconfinder::Beacon_<ContainerAllocator> >::other > & vec) const { vec = this->beacon; }
  ROS_DEPRECATED void set_beacon_vec(const std::vector< ::beaconfinder::Beacon_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::beaconfinder::Beacon_<ContainerAllocator> >::other > & vec) { this->beacon = vec; }
private:
  static const char* __s_getDataType_() { return "beaconfinder/Beacons"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "873d03fb58b312326f8bc5e4bda6e56b"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "#Beacons message for publishing a list of beacons from a laser scan to a topic\n\
Header header\n\
uint8 numBeacons\n\
# A list of Beacons found at this timestamp\n\
Beacon[] beacon\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: beaconfinder/Beacon\n\
# Beacon message type, for a single beacon\n\
\n\
# These IDs go from 0..n, for n beacons in increasing order of size\n\
uint8 ID\n\
\n\
# The x coordinate (robot relative) of the centre of the beacon\n\
float32 x\n\
\n\
# The y coordinate (robot relative) of the centre of the beacon\n\
float32 y\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, numBeacons);
    ros::serialization::serialize(stream, beacon);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, numBeacons);
    ros::serialization::deserialize(stream, beacon);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(numBeacons);
    size += ros::serialization::serializationLength(beacon);
    return size;
  }

  typedef boost::shared_ptr< ::beaconfinder::Beacons_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beaconfinder::Beacons_<ContainerAllocator>  const> ConstPtr;
}; // struct Beacons
typedef  ::beaconfinder::Beacons_<std::allocator<void> > Beacons;

typedef boost::shared_ptr< ::beaconfinder::Beacons> BeaconsPtr;
typedef boost::shared_ptr< ::beaconfinder::Beacons const> BeaconsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::beaconfinder::Beacons_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::beaconfinder::Beacons_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace beaconfinder

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::beaconfinder::Beacons_<ContainerAllocator> > {
  static const char* value() 
  {
    return "873d03fb58b312326f8bc5e4bda6e56b";
  }

  static const char* value(const  ::beaconfinder::Beacons_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x873d03fb58b31232ULL;
  static const uint64_t static_value2 = 0x6f8bc5e4bda6e56bULL;
};

template<class ContainerAllocator>
struct DataType< ::beaconfinder::Beacons_<ContainerAllocator> > {
  static const char* value() 
  {
    return "beaconfinder/Beacons";
  }

  static const char* value(const  ::beaconfinder::Beacons_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::beaconfinder::Beacons_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#Beacons message for publishing a list of beacons from a laser scan to a topic\n\
Header header\n\
uint8 numBeacons\n\
# A list of Beacons found at this timestamp\n\
Beacon[] beacon\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: beaconfinder/Beacon\n\
# Beacon message type, for a single beacon\n\
\n\
# These IDs go from 0..n, for n beacons in increasing order of size\n\
uint8 ID\n\
\n\
# The x coordinate (robot relative) of the centre of the beacon\n\
float32 x\n\
\n\
# The y coordinate (robot relative) of the centre of the beacon\n\
float32 y\n\
\n\
";
  }

  static const char* value(const  ::beaconfinder::Beacons_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::beaconfinder::Beacons_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::beaconfinder::Beacons_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::beaconfinder::Beacons_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.numBeacons);
    stream.next(m.beacon);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Beacons_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beaconfinder::Beacons_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::beaconfinder::Beacons_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "numBeacons: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.numBeacons);
    s << indent << "beacon[]" << std::endl;
    for (size_t i = 0; i < v.beacon.size(); ++i)
    {
      s << indent << "  beacon[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::beaconfinder::Beacon_<ContainerAllocator> >::stream(s, indent + "    ", v.beacon[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // BEACONFINDER_MESSAGE_BEACONS_H

